name: higs
favicon: null
layout_spectrum: 0.9574035862460732
typography_spectrum: 0.9220930894371122
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9361921607051045
  lightness: 0.7687172133009881
  saturation: 0.33232643571682274
  rhythmicContrast: 0.9114179299212992
purpose: []
